import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-gray-800 p-3 flex justify-start">
          <Link className="text-gray-300 p-3" href={"/SSG"}>
            SSG
          </Link>
          <Link className="text-gray-300 p-3" href={"/ISR"}>
            ISR
          </Link>
          <Link className="text-gray-300 p-3" href={"/SSR"}>
            SSR
          </Link>
          <Link className="text-gray-300 p-3" href={"/CSR"}>
            CSR
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
